---
abstract: 'simple job queue manager'
author:
  - 'Atsushi Kobayashi <nekokak _at_ gmail dot com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Qudo
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Class::Data::Inheritable: 0
  DBI: 0
  DBIx::Skinny: 0
  UNIVERSAL::require: 0
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nekokak/qudo.git
version: 0.02
